name: Bug Report (Debugger)
description: Vector Debugger-Related Bugs
type: "Bug"
labels: ["debugger"]
title: "Debugger: <a short description of the Debugger bug>"
body:
  - type: textarea
    attributes:
      label: Summary
      description: Describe the bug with a one line summary, and provide detailed reproduction steps
      value: |
        <!-- Please insert a one line summary of the issue below -->
        SUMMARY_SENTENCE_HERE

        ### Description
        <!--  Describe with sufficient detail to reproduce from a clean Vector install. -->
        Steps to trigger the problem:
        1.
        2.
        3.

        Actual Behavior:
        Expected Behavior:

    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Vector Version and System Specs
      description: 'Run `vector --system-specs` in a terminal and paste the output'
      placeholder: |
        Output of `vector --system-specs`
    validations:
      required: true
