name: Crash Report
description: Vector is crashing or hanging
type: "Crash"
body:
  - type: textarea
    attributes:
      label: Summary
      description: Summarize the issue with detailed reproduction steps
      value: |
        <!-- Begin your issue with a one sentence summary -->
        SUMMARY_SENTENCE_HERE

        ### Description
        <!-- Include all steps necessary to reproduce from a clean Vector installation. Be verbose -->
        Steps to trigger the problem:
        1.
        2.
        3.

        Actual Behavior:
        Expected Behavior:

    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Vector Version and System Specs
      description: 'Run `vector --system-specs` in a terminal and paste the output'
      placeholder: |
        Output of `vector --system-specs`
    validations:
      required: true
  - type: textarea
    attributes:
      label: If applicable, attach your Vector log file to this issue.
      description: |
        macOS: `~/Library/Logs/Vector/Vector.log`
        Linux: `~/.local/share/Vector/logs/Vector.log` (or `$XDG_DATA_HOME/Vector/logs/Vector.log`)
        You can also use the "Open Log" action from the Command Palette to view recent lines.
      value: |
        <details><summary>Vector.log</summary>

        <!-- Paste your log inside the code block. -->
        ```log

        ```

        </details>
    validations:
      required: false
