#!/usr/bin/env bash

set -euxo pipefail
source script/lib/blob-store.sh

# Function for displaying help info
help_info() {
  echo "
Usage: ${0##*/} [options]
Build a release .tar.gz for Linux.

Options:
  -h    Display this help and exit.
  "
}

while getopts 'h' flag
do
    case "${flag}" in
        h)
           help_info
           exit 0
           ;;
    esac
done

export VECTOR_BUNDLE=true

channel=$(<crates/release_channel/RELEASE_CHANNEL)
target_dir="${CARGO_TARGET_DIR:-target}"

version="$(script/get-crate-version vector)"
# Set RELEASE_VERSION so it's compiled into GPUI and it knows about the version.
export RELEASE_VERSION="${version}"

commit=$(git rev-parse HEAD | cut -c 1-7)

version_info=$(rustc --version --verbose)
host_line=$(echo "$version_info" | grep host)
target_triple=${host_line#*: }

# Generate the licenses first, so they can be baked into the binaries
script/generate-licenses

export CC=$(which clang)

# Build binary in release mode
export RUSTFLAGS="${RUSTFLAGS:-} -C link-args=-Wl,--disable-new-dtags,-rpath,\$ORIGIN/../lib"
cargo build --release --target "${target_triple}" --package vector --package cli

# Strip debug symbols and save them for upload to DigitalOcean
objcopy --only-keep-debug "${target_dir}/${target_triple}/release/vector" "${target_dir}/${target_triple}/release/vector.dbg"
objcopy --strip-debug "${target_dir}/${target_triple}/release/vector"
objcopy --strip-debug "${target_dir}/${target_triple}/release/cli"

gzip -f "${target_dir}/${target_triple}/release/vector.dbg"

if [[ -n "${DIGITALOCEAN_SPACES_SECRET_KEY:-}" && -n "${DIGITALOCEAN_SPACES_ACCESS_KEY:-}" ]]; then
    upload_to_blob_store_public \
        "vector-debug-symbols" \
        "${target_dir}/${target_triple}/release/vector.dbg.gz" \
        "$channel/vector-$version-${target_triple}.dbg.gz"
fi

suffix=""
if [ "$channel" != "stable" ]; then
  suffix="-$channel"
fi

# Move everything that should end up in the final package
# into a temp directory.
temp_dir=$(mktemp -d)
vector_dir="${temp_dir}/vector$suffix.app"

# Binary
mkdir -p "${vector_dir}/bin" "${vector_dir}/libexec"
cp "${target_dir}/${target_triple}/release/vector" "${vector_dir}/libexec/vector-editor"
cp "${target_dir}/${target_triple}/release/cli" "${vector_dir}/bin/vector"

# Libs
find_libs() {
    ldd ${target_dir}/${target_triple}/release/vector |\
        cut -d' ' -f3 |\
        grep -v '\<\(libstdc++.so\|libc.so\|libgcc_s.so\|libm.so\|libpthread.so\|libdl.so\|libasound.so\)'
}

mkdir -p "${vector_dir}/lib"
rm -rf "${vector_dir}/lib/*"
cp $(find_libs) "${vector_dir}/lib"

# Icons
mkdir -p "${vector_dir}/share/icons/hicolor/512x512/apps"
cp "crates/vector/resources/app-icon$suffix.png" "${vector_dir}/share/icons/hicolor/512x512/apps/vector.png"
mkdir -p "${vector_dir}/share/icons/hicolor/1024x1024/apps"
cp "crates/vector/resources/app-icon$suffix@2x.png" "${vector_dir}/share/icons/hicolor/1024x1024/apps/vector.png"

# .desktop
export DO_STARTUP_NOTIFY="true"
export APP_CLI="vector"
export APP_ICON="vector"
export APP_ARGS="%U"
if [[ "$channel" == "preview" ]]; then
  export APP_NAME="Vector Preview"
elif [[ "$channel" == "nightly" ]]; then
  export APP_NAME="Vector Nightly"
elif [[ "$channel" == "dev" ]]; then
  export APP_NAME="Vector Devel"
else
  export APP_NAME="Vector"
fi

mkdir -p "${vector_dir}/share/applications"
envsubst < "crates/vector/resources/vector.desktop.in" > "${vector_dir}/share/applications/vector$suffix.desktop"

# Copy generated licenses so they'll end up in archive too
cp "assets/licenses.md" "${vector_dir}/licenses.md"

# Create archive out of everything that's in the temp directory
arch=$(uname -m)
target="linux-${arch}"
if  [[ "$channel" == "dev" ]]; then
  archive="vector-${commit}-${target}.tar.gz"
else
  archive="vector-${target}.tar.gz"
fi

rm -rf "${archive}"
remove_match="vector(-[a-zA-Z0-9]+)?-linux-$(uname -m)\.tar\.gz"
ls "${target_dir}/release" | grep -E ${remove_match} | xargs -d "\n" -I {} rm -f "${target_dir}/release/{}" || true
tar -czvf "${target_dir}/release/$archive" -C ${temp_dir} "vector$suffix.app"
