#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs vector onto your system into ~/.local, making it available as ~/.local/bin/vector.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export VECTOR_CHANNEL=$(<crates/release_channel/RELEASE_CHANNEL)
export VECTOR_UPDATE_EXPLANATION="You need to fetch and rebuild vector in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="zed-linux-${arch}.tar.gz"
export ZED_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
