#!/usr/bin/env bash

set -euxo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <release_version>"
  exit 1
fi

mkdir -p snap/gui

export DO_STARTUP_NOTIFY="true"
export APP_NAME="Vector"
export APP_CLI="vector"
export APP_ICON="\${SNAP}/meta/gui/vector.png"
export APP_ARGS="%U"
envsubst < "crates/vector/resources/vector.desktop.in" > "snap/gui/vector.desktop"
cp "crates/vector/resources/app-icon.png" "snap/gui/vector.png"

RELEASE_VERSION="$1" envsubst < crates/vector/resources/snap/snapcraft.yaml.in > snap/snapcraft.yaml

# Clean seems to be needed to actually check that the snapcraft.yaml
# works.  For example, when a `stage-package` is removed, it will
# still remain on rebuild.
snapcraft clean

snapcraft
